version: '3'
services:
  mysql:
    image: 'mysql:5.7.36'
    user: root
    restart: always
    container_name: mysql
    networks:
      - net_registry
    environment:
     - MYSQL_ROOT_PASSWORD=123456
     - TZ=Asia/Shanghai
    ports:
      - '3306:3306'
    volumes:
      - /ww/app/mysql/config:/etc/mysql
      - /ww/app/mysql/data:/var/lib/mysql
      - /ww/app/mysql/log:/var/log/mysql
      
networks:
  net_registry:
    driver: bridge